import AboutUs from "@/app/Components/AboutUs";

export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <AboutUs/>
    </>
  );
}
