import { electronicProducts } from "../API Services/HomePageAPI";
import HomePage from "../Components/HomePage";

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default async function Home() {

  const products = await electronicProducts();

  return (
    <>
      <HomePage products={products}/>
    </>
  );
}
